/**
 * @file lama_engine.cpp
 * @brief LaMa Inpainting Engine — Implementation
 */

#include "lama_engine.h"
#include <filesystem>
#include <stdexcept>

namespace ocr {

struct LaMaEngine::Impl {
    std::string model_path;
    bool is_ready = false;
    bool is_mock = false;

    // ONNX Runtime session for LaMa model
    // std::unique_ptr<Ort::Session> session;

    Impl(const std::string& model_dir) {
        model_path = model_dir + "/lama_inpaint.onnx";

        if (!std::filesystem::exists(model_path)) {
            // Model not available — inpainting will run in Mock mode
            is_mock = true;
            is_ready = true;
            return;
        }

        // TODO: Initialize ONNX Runtime session for LaMa
        // Ort::SessionOptions opts;
        // opts.SetIntraOpNumThreads(2);
        // session = std::make_unique<Ort::Session>(env, model_path.c_str(), opts);

        is_ready = true;
    }
};

LaMaEngine::LaMaEngine(const std::string& model_dir)
    : impl_(std::make_unique<Impl>(model_dir)) {
}

LaMaEngine::~LaMaEngine() = default;

bool LaMaEngine::isReady() const {
    return impl_ && impl_->is_ready;
}

Image LaMaEngine::inpaint(const Image& image, const Image& mask) {
    if (!isReady() || image.empty() || mask.empty()) {
        return image; // Return original if inpainting unavailable
    }

    if (impl_->is_mock) {
        // Mock inpainting: Paint masked regions white (255, 255, 255)
        Image result = image;
        for (int y = 0; y < image.height(); y++) {
            for (int x = 0; x < image.width(); x++) {
                const uint8_t* mask_px = mask.pixel(x, y);
                // Mask pixels generated by generateMask are white (255)
                if (mask_px[0] > 128) {
                    uint8_t* dst_px = result.pixel(x, y);
                    dst_px[0] = 255;
                    dst_px[1] = 255;
                    dst_px[2] = 255;
                }
            }
        }
        return result;
    }

    // TODO: Implement LaMa inference via ONNX Runtime
    //
    // Pipeline:
    // 1. Prepare input tensors:
    //    - image: [1, 3, H, W] normalized to [0, 1]
    //    - mask:  [1, 1, H, W] binary (0 or 1)
    //
    // 2. Run inference:
    //    - output: [1, 3, H, W] inpainted image
    //
    // 3. Post-process:
    //    - Denormalize output to [0, 255]
    //    - Merge with original (only replace masked regions)
    //    - Convert back to RGBA

    return image; // Passthrough until ONNX Runtime integration
}

} // namespace ocr
