name: OCREditor
options:
  bundleIdPrefix: com.hauchiehlin.ocreditor
targets:
  OCREditor:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - OCREditor
      - path: ../../core/src
        type: group
        name: Core
      - path: ../../core/include
        type: group
        name: Include
      - path: ../../models
        type: folder
        buildPhase: resources
      - path: ../../core/assets/fonts
        type: folder
        buildPhase: resources
    infoPlist: OCREditor/Info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.hauchiehlin.ocreditor
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: 6UJ8GS752W
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ENABLE_PREVIEWS: YES
      SWIFT_VERSION: 5.0
      CURRENT_PROJECT_VERSION: "4"
      MARKETING_VERSION: "1.0.1"
      SWIFT_OBJC_BRIDGING_HEADER: OCREditor/OCREditor-Bridging-Header.h
      CODE_SIGN_ENTITLEMENTS[sdk=macosx*]: OCREditor/OCREditor.entitlements
      TARGETED_DEVICE_FAMILY: "1,2"
      SUPPORTED_PLATFORMS: "iphoneos iphonesimulator macosx"
      MACOSX_DEPLOYMENT_TARGET: "14.0"
      INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
      HEADER_SEARCH_PATHS: '"$(inherited)" "$(SRCROOT)/../../core/include" "$(SRCROOT)/../../core/src"'
      CLANG_CXX_LANGUAGE_STANDARD: "c++17"
      GCC_PREPROCESSOR_DEFINITIONS: "OCR_ENABLE_GPU=1"
      OTHER_LDFLAGS: "-lsqlite3"

