using System;
using System.Collections.Generic;
using System.Windows;

namespace OCREditor
{
    public static class LocalizationManager
    {
        public static readonly List<string> SupportedLanguages = new List<string>
        {
            "English", "繁體中文", "简体中文", "日本語", "한국어", "ไทย", "Español", "Português", "Bahasa Melayu", "Русский", "Deutsch"
        };

        private static readonly Dictionary<string, Dictionary<string, string>> _dictionaries = new Dictionary<string, Dictionary<string, string>>
        {
            {
                "English", new Dictionary<string, string>
                {
                    { "FileMenu", "File" },
                    { "EditMenu", "Edit" },
                    { "ViewMenu", "View" },
                    { "SettingsMenu", "Settings" },
                    { "LanguageMenu", "Language" },
                    { "LoadImage", "📂 Open Image" },
                    { "SaveImage", "💾 Save Result" },
                    { "InsertText", "📝 Insert Text" },
                    { "ApplyDefaultFont", "🔤 Apply Default Font to All" },
                    { "Undo", "↩️ Undo" },
                    { "Redo", "↪️ Redo" },
                    { "ShowLeftPanel", "📋 Show Layers Panel" },
                    { "ShowRightPanel", "⚙️ Show Properties Panel" },
                    { "Zoom", "🔍 Zoom:" },
                    { "DocumentStatus", "Document Status" },
                    { "InteractiveLayers", "Interactive Text Layers" },
                    { "TextFormattingPanel", "Text Formatting Panel" },
                    { "EditContent", "Edit Content" },
                    { "ParagraphFormat", "Paragraph Format" },
                    { "Size", "Size: " },
                    { "Font", "Font: " },
                    { "ColorPresets", "Color Presets: " },
                    { "Bold", " Bold " },
                    { "Italic", " Italic " },
                    { "Operations", "Operations" },
                    { "TranslateBtn", "🌐 Translate to Current Language" },
                    { "RemoveText", "🗑️ Remove Text Region" },
                    { "Tip", "Tip: If AI missed a word, click-and-drag directly on the image to draw a manual text box!" },
                    { "AppTitle", "OCR Visual Editor Professional — Powered by Windows AI Platform" },
                    { "WaitMessage", "Processing... Please wait." },
                    { "EditTextHere", "Edit text here" },
                    { "ManuallyDrawnText", "[Manually Drawn Text]" }
                }
            },
            {
                "繁體中文", new Dictionary<string, string>
                {
                    { "FileMenu", "檔案" },
                    { "EditMenu", "編輯" },
                    { "ViewMenu", "檢視" },
                    { "SettingsMenu", "設定" },
                    { "LanguageMenu", "語言" },
                    { "LoadImage", "📂 開啟圖片" },
                    { "SaveImage", "💾 儲存結果" },
                    { "InsertText", "📝 插入文字" },
                    { "ApplyDefaultFont", "🔤 套用預設字體至全部" },
                    { "Undo", "↩️ 復原" },
                    { "Redo", "↪️ 重做" },
                    { "ShowLeftPanel", "📋 顯示圖層面板" },
                    { "ShowRightPanel", "⚙️ 顯示屬性面板" },
                    { "Zoom", "🔍 縮放：" },
                    { "DocumentStatus", "文件狀態" },
                    { "InteractiveLayers", "互動式文字圖層" },
                    { "TextFormattingPanel", "文字格式面板" },
                    { "EditContent", "編輯內容" },
                    { "ParagraphFormat", "段落格式" },
                    { "Size", "大小：" },
                    { "Font", "字體：" },
                    { "ColorPresets", "快捷色彩：" },
                    { "Bold", " 粗體 " },
                    { "Italic", " 斜體 " },
                    { "Operations", "操作" },
                    { "TranslateBtn", "🌐 翻譯為目前語言" },
                    { "RemoveText", "🗑️ 移除文字區塊" },
                    { "Tip", "提示：如果 AI 漏抓了文字，請直接在圖片上拖曳框選來手動建立文字方塊！" },
                    { "AppTitle", "OCR 視覺化編輯器專業版 — AI 平台驅動" },
                    { "WaitMessage", "處理中... 請稍候。" },
                    { "EditTextHere", "在此編輯文字" },
                    { "ManuallyDrawnText", "[手動框選文字]" }
                }
            },
            {
                "简体中文", new Dictionary<string, string>
                {
                    { "FileMenu", "文件" },
                    { "EditMenu", "编辑" },
                    { "ViewMenu", "视图" },
                    { "SettingsMenu", "设置" },
                    { "LanguageMenu", "语言" },
                    { "LoadImage", "📂 打开图片" },
                    { "SaveImage", "💾 保存结果" },
                    { "InsertText", "📝 插入文本" },
                    { "ApplyDefaultFont", "🔤 应用默认字体至全部" },
                    { "Undo", "↩️ 撤销" },
                    { "Redo", "↪️ 重做" },
                    { "ShowLeftPanel", "📋 显示图层面板" },
                    { "ShowRightPanel", "⚙️ 显示属性面板" },
                    { "Zoom", "🔍 缩放：" },
                    { "DocumentStatus", "文档状态" },
                    { "InteractiveLayers", "交互式文本图层" },
                    { "TextFormattingPanel", "文本格式面板" },
                    { "EditContent", "编辑内容" },
                    { "ParagraphFormat", "段落格式" },
                    { "Size", "大小：" },
                    { "Font", "字体：" },
                    { "ColorPresets", "快捷色彩：" },
                    { "Bold", " 粗体 " },
                    { "Italic", " 斜体 " },
                    { "Operations", "操作" },
                    { "TranslateBtn", "🌐 翻译为当前语言" },
                    { "RemoveText", "🗑️ 移除文本区块" },
                    { "Tip", "提示：如果 AI 漏抓了文字，请直接在图片上拖拽框选来手动创建文本框！" },
                    { "AppTitle", "OCR 可视化编辑器专业版 — AI 平台驱动" },
                    { "WaitMessage", "处理中... 请稍候。" },
                    { "EditTextHere", "在此编辑文字" },
                    { "ManuallyDrawnText", "[手动框选文字]" }
                }
            },
            {
                "日本語", new Dictionary<string, string>
                {
                    { "FileMenu", "ファイル" },
                    { "EditMenu", "編集" },
                    { "ViewMenu", "表示" },
                    { "SettingsMenu", "設定" },
                    { "LanguageMenu", "言語" },
                    { "LoadImage", "📂 画像を開く" },
                    { "SaveImage", "💾 結果を保存" },
                    { "InsertText", "📝 テキストを挿入" },
                    { "ApplyDefaultFont", "🔤 全てにデフォルトフォントを適用" },
                    { "Undo", "↩️ 元に戻す" },
                    { "Redo", "↪️ やり直し" },
                    { "ShowLeftPanel", "📋 レイヤーパネルを表示" },
                    { "ShowRightPanel", "⚙️ プロパティパネルを表示" },
                    { "Zoom", "🔍 ズーム:" },
                    { "DocumentStatus", "ドキュメントの状態" },
                    { "InteractiveLayers", "インタラクティブなテキストレイヤー" },
                    { "TextFormattingPanel", "テキストフォーマットパネル" },
                    { "EditContent", "コンテンツを編集" },
                    { "ParagraphFormat", "段落フォーマット" },
                    { "Size", "サイズ: " },
                    { "Font", "フォント: " },
                    { "ColorPresets", "カラープリセット: " },
                    { "Bold", " 太字 " },
                    { "Italic", " 斜体 " },
                    { "Operations", "操作" },
                    { "TranslateBtn", "🌐 現在の言語に翻訳" },
                    { "RemoveText", "🗑️ テキスト領域を削除" },
                    { "Tip", "ヒント: AIが文字を見逃した場合は、画像上で直接ドラッグして手動でテキストボックスを作成してください！" },
                    { "AppTitle", "OCR ビジュアルエディター プロ — AI プラットフォーム搭載" },
                    { "WaitMessage", "処理中... お待ちください。" },
                    { "EditTextHere", "ここでテキストを編集" },
                    { "ManuallyDrawnText", "[手動で描画されたテキスト]" }
                }
            },
            {
                "한국어", new Dictionary<string, string>
                {
                    { "FileMenu", "파일" },
                    { "EditMenu", "편집" },
                    { "ViewMenu", "보기" },
                    { "SettingsMenu", "설정" },
                    { "LanguageMenu", "언어" },
                    { "LoadImage", "📂 이미지 열기" },
                    { "SaveImage", "💾 결과 저장" },
                    { "InsertText", "📝 텍스트 삽입" },
                    { "ApplyDefaultFont", "🔤 모두 기본 글꼴 적용" },
                    { "Undo", "↩️ 실행 취소" },
                    { "Redo", "↪️ 다시 실행" },
                    { "ShowLeftPanel", "📋 레이어 패널 표시" },
                    { "ShowRightPanel", "⚙️ 속성 패널 표시" },
                    { "Zoom", "🔍 확대/축소:" },
                    { "DocumentStatus", "문서 상태" },
                    { "InteractiveLayers", "대화형 텍스트 레이어" },
                    { "TextFormattingPanel", "텍스트 서식 패널" },
                    { "EditContent", "콘텐츠 편집" },
                    { "ParagraphFormat", "단락 서식" },
                    { "Size", "크기: " },
                    { "Font", "글꼴: " },
                    { "ColorPresets", "색상 사전 설정: " },
                    { "Bold", " 굵게 " },
                    { "Italic", " 기울임꼴 " },
                    { "Operations", "작업" },
                    { "TranslateBtn", "🌐 현재 언어로 번역" },
                    { "RemoveText", "🗑️ 텍스트 영역 삭제" },
                    { "Tip", "팁: AI가 문자를 놓친 경우, 이미지 위에서 직접 드래그하여 수동으로 텍스트 상자를 만드세요!" },
                    { "AppTitle", "OCR 시각 편집기 프로 — AI 플랫폼 구동" },
                    { "WaitMessage", "처리 중... 기다려 주십시오." },
                    { "EditTextHere", "여기에 텍스트 편집" },
                    { "ManuallyDrawnText", "[수동으로 그린 텍스트]" }
                }
            },
            {
                "ไทย", new Dictionary<string, string>
                {
                    { "FileMenu", "ไฟล์" },
                    { "EditMenu", "แก้ไข" },
                    { "ViewMenu", "มุมมอง" },
                    { "SettingsMenu", "การตั้งค่า" },
                    { "LanguageMenu", "ภาษา" },
                    { "LoadImage", "📂 เปิดรูปภาพ" },
                    { "SaveImage", "💾 บันทึกผลลัพธ์" },
                    { "InsertText", "📝 แทรกข้อความ" },
                    { "ApplyDefaultFont", "🔤 ใช้ฟอนต์เริ่มต้นทั้งหมด" },
                    { "Undo", "↩️ เลิกทำ" },
                    { "Redo", "↪️ ทำซ้ำ" },
                    { "ShowLeftPanel", "📋 แสดงแผงเลเยอร์" },
                    { "ShowRightPanel", "⚙️ แสดงแผงคุณสมบัติ" },
                    { "Zoom", "🔍 ซูม:" },
                    { "DocumentStatus", "สถานะเอกสาร" },
                    { "InteractiveLayers", "เลเยอร์ข้อความโต้ตอบ" },
                    { "TextFormattingPanel", "แผงจัดรูปแบบข้อความ" },
                    { "EditContent", "แก้ไขเนื้อหา" },
                    { "ParagraphFormat", "รูปแบบย่อหน้า" },
                    { "Size", "ขนาด: " },
                    { "Font", "ฟอนต์: " },
                    { "ColorPresets", "สีที่ตั้งไว้: " },
                    { "Bold", " ตัวหนา " },
                    { "Italic", " ตัวเอียง " },
                    { "Operations", "การดำเนินการ" },
                    { "TranslateBtn", "🌐 แปลเป็นภาษาปัจจุบัน" },
                    { "RemoveText", "🗑️ ลบพื้นที่ข้อความ" },
                    { "Tip", "เคล็ดลับ: หาก AI พลาดข้อความไป ให้ลากคลิกบนภาพเพื่อสร้างกล่องข้อความด้วยตนเอง!" },
                    { "AppTitle", "เครื่องมือแก้ไขภาพ OCR ระดับโปร — ขับเคลื่อนด้วย AI" },
                    { "WaitMessage", "กำลังประมวลผล... โปรดรอสักครู่" },
                    { "EditTextHere", "แก้ไขข้อความที่นี่" },
                    { "ManuallyDrawnText", "[ข้อความที่วาดด้วยตนเอง]" }
                }
            },
            {
                "Español", new Dictionary<string, string>
                {
                    { "FileMenu", "Archivo" },
                    { "EditMenu", "Editar" },
                    { "ViewMenu", "Ver" },
                    { "SettingsMenu", "Configuración" },
                    { "LanguageMenu", "Idioma" },
                    { "LoadImage", "📂 Abrir imagen" },
                    { "SaveImage", "💾 Guardar resultado" },
                    { "InsertText", "📝 Insertar texto" },
                    { "ApplyDefaultFont", "🔤 Aplicar fuente a todos" },
                    { "Undo", "↩️ Deshacer" },
                    { "Redo", "↪️ Rehacer" },
                    { "ShowLeftPanel", "📋 Mostrar panel de capas" },
                    { "ShowRightPanel", "⚙️ Mostrar panel de prop." },
                    { "Zoom", "🔍 Zoom:" },
                    { "DocumentStatus", "Estado del documento" },
                    { "InteractiveLayers", "Capas de texto interactivas" },
                    { "TextFormattingPanel", "Panel de formato" },
                    { "EditContent", "Editar contenido" },
                    { "ParagraphFormat", "Formato de párrafo" },
                    { "Size", "Tamaño: " },
                    { "Font", "Fuente: " },
                    { "ColorPresets", "Colores: " },
                    { "Bold", " Negrita " },
                    { "Italic", " Cursiva " },
                    { "Operations", "Operaciones" },
                    { "TranslateBtn", "🌐 Traducir al idioma actual" },
                    { "RemoveText", "🗑️ Eliminar región" },
                    { "Tip", "Sugerencia: Si la IA omitió un texto, arrastre sobre la imagen para crear un cuadro manualmente." },
                    { "AppTitle", "Editor Visual OCR Profesional — Impulsado por AI" },
                    { "WaitMessage", "Procesando... Por favor, espere." },
                    { "EditTextHere", "Editar texto aquí" },
                    { "ManuallyDrawnText", "[Texto dibujado manualmente]" }
                }
            },
            {
                "Português", new Dictionary<string, string>
                {
                    { "FileMenu", "Arquivo" },
                    { "EditMenu", "Editar" },
                    { "ViewMenu", "Exibir" },
                    { "SettingsMenu", "Configurações" },
                    { "LanguageMenu", "Idioma" },
                    { "LoadImage", "📂 Abrir Imagem" },
                    { "SaveImage", "💾 Salvar Resultado" },
                    { "InsertText", "📝 Inserir Texto" },
                    { "ApplyDefaultFont", "🔤 Aplicar Fonte a Todos" },
                    { "Undo", "↩️ Desfazer" },
                    { "Redo", "↪️ Refazer" },
                    { "ShowLeftPanel", "📋 Mostrar Painel de Camadas" },
                    { "ShowRightPanel", "⚙️ Mostrar Painel de Prop." },
                    { "Zoom", "🔍 Zoom:" },
                    { "DocumentStatus", "Status do Documento" },
                    { "InteractiveLayers", "Camadas de Texto" },
                    { "TextFormattingPanel", "Painel de Formatação" },
                    { "EditContent", "Editar Conteúdo" },
                    { "ParagraphFormat", "Formato de Parágrafo" },
                    { "Size", "Tamanho: " },
                    { "Font", "Fonte: " },
                    { "ColorPresets", "Cores: " },
                    { "Bold", " Negrito " },
                    { "Italic", " Itálico " },
                    { "Operations", "Operações" },
                    { "TranslateBtn", "🌐 Traduzir para idioma atual" },
                    { "RemoveText", "🗑️ Remover região" },
                    { "Tip", "Dica: Se a IA não reconhecer um texto, arraste sobre a imagem para criar uma caixa manual!" },
                    { "AppTitle", "Editor Visual OCR Profissional — Desenvolvido por IA" },
                    { "WaitMessage", "Processando... Por favor, aguarde." },
                    { "EditTextHere", "Editar texto aqui" },
                    { "ManuallyDrawnText", "[Texto desenhado manualmente]" }
                }
            },
            {
                "Bahasa Melayu", new Dictionary<string, string>
                {
                    { "FileMenu", "Fail" },
                    { "EditMenu", "Edit" },
                    { "ViewMenu", "Lihat" },
                    { "SettingsMenu", "Tetapan" },
                    { "LanguageMenu", "Bahasa" },
                    { "LoadImage", "📂 Buka Imej" },
                    { "SaveImage", "💾 Simpan Hasil" },
                    { "InsertText", "📝 Masukkan Teks" },
                    { "ApplyDefaultFont", "🔤 Guna Fon Lalai" },
                    { "Undo", "↩️ Buat Asal" },
                    { "Redo", "↪️ Buat Semula" },
                    { "ShowLeftPanel", "📋 Tunjuk Panel Lapisan" },
                    { "ShowRightPanel", "⚙️ Tunjuk Panel Ciri" },
                    { "Zoom", "🔍 Zum:" },
                    { "DocumentStatus", "Status Dokumen" },
                    { "InteractiveLayers", "Lapisan Teks Interaktif" },
                    { "TextFormattingPanel", "Panel Pemformatan" },
                    { "EditContent", "Edit Kandungan" },
                    { "ParagraphFormat", "Format Perenggan" },
                    { "Size", "Saiz: " },
                    { "Font", "Fon: " },
                    { "ColorPresets", "Warna: " },
                    { "Bold", " Tebal " },
                    { "Italic", " Condong " },
                    { "Operations", "Operasi" },
                    { "TranslateBtn", "🌐 Terjemah ke bahasa semasa" },
                    { "RemoveText", "🗑️ Buang kawasan teks" },
                    { "Tip", "Petua: Jika AI terlepas teks, seret pada imej untuk mencipta kotak teks manual!" },
                    { "AppTitle", "Editor Visual OCR Profesional — Dikuasakan oleh AI" },
                    { "WaitMessage", "Sedang memproses... Sila tunggu." },
                    { "EditTextHere", "Edit teks di sini" },
                    { "ManuallyDrawnText", "[Teks Dilukis Manual]" }
                }
            },
            {
                "Русский", new Dictionary<string, string>
                {
                    { "FileMenu", "Файл" },
                    { "EditMenu", "Правка" },
                    { "ViewMenu", "Вид" },
                    { "SettingsMenu", "Настройки" },
                    { "LanguageMenu", "Язык" },
                    { "LoadImage", "📂 Открыть изобр." },
                    { "SaveImage", "💾 Сохранить" },
                    { "InsertText", "📝 Вставить текст" },
                    { "ApplyDefaultFont", "🔤 Применить шрифт ко всем" },
                    { "Undo", "↩️ Отменить" },
                    { "Redo", "↪️ Вернуть" },
                    { "ShowLeftPanel", "📋 Панель слоев" },
                    { "ShowRightPanel", "⚙️ Панель свойств" },
                    { "Zoom", "🔍 Масштаб:" },
                    { "DocumentStatus", "Статус документа" },
                    { "InteractiveLayers", "Интерактивные слои" },
                    { "TextFormattingPanel", "Панель форматирования" },
                    { "EditContent", "Редактировать текст" },
                    { "ParagraphFormat", "Формат абзаца" },
                    { "Size", "Размер: " },
                    { "Font", "Шрифт: " },
                    { "ColorPresets", "Цвета: " },
                    { "Bold", " Жирный " },
                    { "Italic", " Курсив " },
                    { "Operations", "Операции" },
                    { "TranslateBtn", "🌐 Перевести на текущий язык" },
                    { "RemoveText", "🗑️ Удалить область" },
                    { "Tip", "Совет: Если ИИ пропустил текст, перетащите мышью по изображению, чтобы создать блок вручную!" },
                    { "AppTitle", "Профессиональный визуальный редактор OCR — на базе ИИ" },
                    { "WaitMessage", "Обработка... Пожалуйста, подождите." },
                    { "EditTextHere", "Редактировать текст здесь" },
                    { "ManuallyDrawnText", "[Введено вручную]" }
                }
            },
            {
                "Deutsch", new Dictionary<string, string>
                {
                    { "FileMenu", "Datei" },
                    { "EditMenu", "Bearbeiten" },
                    { "ViewMenu", "Ansicht" },
                    { "SettingsMenu", "Einstellungen" },
                    { "LanguageMenu", "Sprache" },
                    { "LoadImage", "📂 Bild öffnen" },
                    { "SaveImage", "💾 Ergebnis speichern" },
                    { "InsertText", "📝 Text einfügen" },
                    { "ApplyDefaultFont", "🔤 Standardschriftart auf alle anwenden" },
                    { "Undo", "↩️ Rückgängig" },
                    { "Redo", "↪️ Wiederholen" },
                    { "ShowLeftPanel", "📋 Ebenen-Panel anzeigen" },
                    { "ShowRightPanel", "⚙️ Eigenschaften anzeigen" },
                    { "Zoom", "🔍 Zoom:" },
                    { "DocumentStatus", "Dokumentenstatus" },
                    { "InteractiveLayers", "Interaktive Textebenen" },
                    { "TextFormattingPanel", "Textformatierung" },
                    { "EditContent", "Inhalt bearbeiten" },
                    { "ParagraphFormat", "Absatzformat" },
                    { "Size", "Größe: " },
                    { "Font", "Schriftart: " },
                    { "ColorPresets", "Farben: " },
                    { "Bold", " Fett " },
                    { "Italic", " Kursiv " },
                    { "Operations", "Operationen" },
                    { "TranslateBtn", "🌐 In aktuelle Sprache übersetzen" },
                    { "RemoveText", "🗑️ Textbereich entfernen" },
                    { "Tip", "Tipp: Wenn die KI einen Text übersehen hat, ziehen Sie ein Feld auf dem Bild, um ihn manuell zu erstellen!" },
                    { "AppTitle", "OCR Visual Editor Professional — KI-gestützt" },
                    { "WaitMessage", "Wird bearbeitet... Bitte warten." },
                    { "EditTextHere", "Text hier bearbeiten" },
                    { "ManuallyDrawnText", "[Manuell gezeichneter Text]" }
                }
            }
        };

        public static void ApplyLanguage(string language)
        {
            if (!_dictionaries.ContainsKey(language)) return;

            var dict = _dictionaries[language];
            foreach (var kvp in dict)
            {
                Application.Current.Resources[kvp.Key] = kvp.Value;
            }
        }
    }
}
